AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: Export cloudWatch logs to S3
Parameters:
    Environment:
        Type: String
        Default: dev
        AllowedValues:
            - dev
            - int
            - uat
            - prd
        Description: Name of the environment (AllowedValues- dev, int, uat, prd)
    DESTINATIONBUCKET:
        Type: String
        Description: Name of the new bucket where cloudwatch logs are to be exported
    GROUPNAME:
        Type: String
        Description: Name of the cloudWatch log group which has to be exported
    NUMBEROFDAYS:
        Type: String
        Description: If today is November 21st and NUMBEROFDAYS = 1, November 20th logs will be exported. (e.g. 2)
    SUBSCRIBEREMAIL:
        Type: String
        Description: Email address who will receive the failure email

Resources: 
  
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Description: Bucket where cloudwatch logs are to be exported
    Properties:
      BucketName: !Ref DESTINATIONBUCKET
          
  MyS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyS3Bucket
      PolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: "logs.ap-southeast-2.amazonaws.com"
          Action: s3:GetBucketAcl
          Resource: !Sub arn:aws:s3:::${MyS3Bucket}
        - Effect: Allow
          Principal:
            Service: "logs.ap-southeast-2.amazonaws.com"
          Action: s3:PutObject
          Resource: !Sub arn:aws:s3:::${MyS3Bucket}/*
          Condition:
            StringEquals:
              s3:x-amz-acl: bucket-owner-full-control
  LambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName:  !Join ['-', [!Ref Environment, 'export', 'cloudWatch', 'logs', 'to', 'S3', 'role']]
      Tags:
        - Key: Name
          Value: !Join ['-', [!Ref Environment, 'export', 'cloudWatch', 'logs', 'to', 'S3']]
        - Key: environment
          Value: !Ref Environment
        - Key: cloudformation:stack
          Value: !Sub '${AWS::StackName}'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
        - 'arn:aws:iam::aws:policy/CloudWatchLogsFullAccess'
        - 'arn:aws:iam::aws:policy/CloudWatchEventsFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonSNSFullAccess'
        
  MySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Join ['-', [!Ref Environment, 'cloudWatch', 'logs', 'to', 'S3', 'topic']]
      DisplayName: !Join [' ', [!Join ['-', [!Ref Environment, 'cloudWatch', 'logs', 'to', 'S3', 'topic']], 'failure email with input event payload']]
      Subscription:
        - Endpoint: !Ref SUBSCRIBEREMAIL
          Protocol: email
      
  Function:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: !Join ['-', [!Ref Environment, 'cloudWatch', 'logs', 'to', 'S3', 'lambda']]
      Code:
        ZipFile: !Sub |
          import boto3
          import os
          import datetime
          
          GROUPNAME = os.environ['GROUPNAME']
          DESTINATIONBUCKET = os.environ['DESTINATIONBUCKET']
          NUMBEROFDAYS = os.environ['NUMBEROFDAYS']
          numberOfDays = int(NUMBEROFDAYS)
          
          today = datetime.datetime.now()
          start = today - datetime.timedelta(days=numberOfDays)
          end = today - datetime.timedelta(days=numberOfDays - 1)          
          fromTimestamp = int(start.timestamp() * 1000)
          toTimestamp = int(end.timestamp() * 1000)  
          BUCKET_PREFIX = start.strftime('%Y{0}%m{0}%d').format(os.path.sep)
          
          def lambda_handler(event, context):
              client = boto3.client('logs')
              client.create_export_task(
                   logGroupName=GROUPNAME,
                   fromTime=fromTimestamp,
                   to=toTimestamp,
                   destination=DESTINATIONBUCKET,
                   destinationPrefix=BUCKET_PREFIX
                  )          	

      Handler: index.lambda_handler
      DeadLetterConfig: 
        TargetArn: !Ref MySNSTopic
      Role: !GetAtt 
        - LambdaRole
        - Arn
      Runtime: python3.8
      Environment:
        Variables:
          DESTINATIONBUCKET: !Ref DESTINATIONBUCKET
          GROUPNAME: !Ref GROUPNAME
          NUMBEROFDAYS : !Ref NUMBEROFDAYS 
      Timeout: 15
      Description: A lambda to export cloudWatch logs to S3
      Tags:
        - Key: Name
          Value: !Join ['-', [!Ref Environment, 'cloudWatch', 'logs', 'to', 'S3']]
        - Key: environment
          Value: !Ref Environment
        - Key: cloudformation:stack
          Value: !Sub '${AWS::StackName}'
